"use strict";class CultsBoonsPage extends ListPage{constructor(){const a=SourceFilter.getInstance(),b=new Filter({header:"Type",items:["Cult","Demonic Boon"]});super({dataSource:"data/cultsboons.json",filters:[a,b],filterSource:a,listClass:"cultsboons",sublistClass:"subcultsboons",dataProps:["cult","boon"]}),this._sourceFilter=a,this._typeFilter=b}getListItem(a,b,c){a.type=a.type||("cult"===a.__prop?"Cult":"Demonic Boon"),c||(this._sourceFilter.addItem(a.source),this._typeFilter.addItem(a.type));const d=document.createElement("li");d.className=`row ${c?"row--blacklisted":""}`;const e=Parser.sourceJsonToAbv(a.source),f=UrlUtil.autoEncodeHash(a);d.innerHTML=`<a href="#${f}" class="lst--border">
			<span class="col-3 text-center pl-0">${a.type}</span>
			<span class="bold col-7">${a.name}</span>
			<span class="col-2 text-center ${Parser.sourceJsonToColor(a.source)} pr-0" title="${Parser.sourceJsonToFull(a.source)}" ${BrewUtil.sourceJsonToStyle(a.source)}>${e}</span>
		</a>`;const g=new ListItem(b,d,a.name,{hash:f,source:e,type:a.type},{uniqueId:a.uniqueId?a.uniqueId:b,isExcluded:c});return d.addEventListener("click",a=>this._list.doSelect(g,a)),d.addEventListener("contextmenu",a=>ListUtil.openContextMenu(a,this._list,g)),g}handleFilterChange(){const a=this._filterBox.getValues();this._list.filter(b=>{const c=this._dataList[b.ix];return this._filterBox.toDisplay(a,c.source,c.type)}),FilterBox.selectFirstVisible(this._dataList)}getSublistItem(a,b){const c=UrlUtil.autoEncodeHash(a),d=$(`<li class="row">
			<a href="#${c}" class="lst--border">
				<span class="col-3 text-center pl-0">${a.type}</span>
				<span class="bold col-9 pr-0">${a.name}</span>
			</a>
		</li>`).contextmenu(a=>ListUtil.openSubContextMenu(a,e)),e=new ListItem(b,d,a.name,{hash:c,type:a.__prop});return e}doLoadHash(a){const b=this._dataList[a];$("#pagecontent").empty().append(RenderCultsBoons.$getRenderedCultBoon(b)),ListUtil.updateSelected()}async pDoLoadSubHash(a){a=this._filterBox.setFromSubHashes(a),await ListUtil.pSetFromSubHashes(a)}}const cultsBoonsPage=new CultsBoonsPage;window.addEventListener("load",()=>cultsBoonsPage.pOnLoad());