"use strict";class LanguagesPage extends ListPage{constructor(){const a=SourceFilter.getInstance(),b=new Filter({header:"Type",items:["standard","exotic","secret"],itemSortFn:null,displayFn:StrUtil.uppercaseFirst}),c=new Filter({header:"Script",displayFn:StrUtil.uppercaseFirst}),d=new Filter({header:"Miscellaneous",items:["SRD"]});super({dataSource:"data/languages.json",filters:[a,b,c,d],filterSource:a,listClass:"languages",sublistClass:"sublanguages",dataProps:["language"]}),this._sourceFilter=a,this._scriptFilter=c}getListItem(a,b,c){a._fMisc=a.srd?["SRD"]:[],c||(this._sourceFilter.addItem(a.source),this._scriptFilter.addItem(a.script));const d=document.createElement("li");d.className=`row ${c?"row--blacklisted":""}`;const e=Parser.sourceJsonToAbv(a.source),f=UrlUtil.autoEncodeHash(a);d.innerHTML=`<a href="#${f}" class="lst--border">
			<span class="col-6 bold pl-0">${a.name}</span>
			<span class="col-2 text-center">${(a.type||"\u2014").uppercaseFirst()}</span>
			<span class="col-2 text-center">${(a.script||"\u2014").toTitleCase()}</span>
			<span class="col-2 text-center ${Parser.sourceJsonToColor(a.source)} pr-0" title="${Parser.sourceJsonToFull(a.source)}" ${BrewUtil.sourceJsonToStyle(a.source)}>${e}</span>
		</a>`;const g=new ListItem(b,d,a.name,{hash:f,source:e,dialects:a.dialects||[],type:a.type||"",script:a.script||""},{uniqueId:a.uniqueId?a.uniqueId:b,isExcluded:c});return d.addEventListener("click",a=>this._list.doSelect(g,a)),d.addEventListener("contextmenu",a=>ListUtil.openContextMenu(a,this._list,g)),g}handleFilterChange(){const a=this._filterBox.getValues();this._list.filter(b=>{const c=this._dataList[b.ix];return this._filterBox.toDisplay(a,c.source,c.type,c.script,c._fMisc)}),FilterBox.selectFirstVisible(this._dataList)}getSublistItem(a,b){const c=UrlUtil.autoEncodeHash(a),d=$(`<li class="row">
			<a href="#${c}" class="lst--border">
				<span class="bold col-8 pl-0">${a.name}</span>
				<span class="col-2 text-center">${(a.type||"\u2014").uppercaseFirst()}</span>
				<span class="col-2 text-center pr-0">${(a.script||"\u2014").toTitleCase()}</span>
			</a>
		</li>`).contextmenu(a=>ListUtil.openSubContextMenu(a,e)),e=new ListItem(b,d,a.name,{hash:c,type:a.type||"",script:a.script||""});return e}doLoadHash(a){const b=$("#pagecontent").empty(),c=this._dataList[a],d=Renderer.utils.tabButton("Traits",()=>{},function(){b.append(RenderLanguages.$getRenderedLanguage(c))}),e=Renderer.utils.tabButton("Images",()=>{},function(a){return Renderer.utils.pBuildFluffTab(a,b,c,a=>c.fluff||a.languageFluff.find(a=>c.name===a.name&&c.source===a.source),`data/fluff-languages.json`,()=>!0)}.bind(null,!0));Renderer.utils.bindTabButtons(d,e),ListUtil.updateSelected()}async pDoLoadSubHash(a){a=this._filterBox.setFromSubHashes(a),await ListUtil.pSetFromSubHashes(a)}}const languagesPage=new LanguagesPage;window.addEventListener("load",()=>languagesPage.pOnLoad());